/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2205 from the
 * contents of FormalInput.xs. Do not edit this file, edit FormalInput.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "FormalInput.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <parser.h>

#include "const-c.inc"

typedef struct parseError ParseError;

#line 23 "FormalInput.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 75 "FormalInput.c"

/* INCLUDE:  Including 'const-xs.inc' from 'FormalInput.xs' */


XS(XS_FormalInput_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_FormalInput_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 104 "FormalInput.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid FormalInput macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined FormalInput macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing FormalInput macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 180 "FormalInput.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'FormalInput.xs' from 'const-xs.inc' */


XS(XS_FormalInput_parserValidate); /* prototype to pass -Wmissing-prototypes */
XS(XS_FormalInput_parserValidate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "buf");
    {
	const char*	buf = (const char *)SvPV_nolen(ST(0));
	ParseError *	RETVAL;

	RETVAL = parserValidate(buf);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "ParseErrorPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_FormalInput_errorMessageByCode); /* prototype to pass -Wmissing-prototypes */
XS(XS_FormalInput_errorMessageByCode)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "errCode");
    {
	int	errCode = (int)SvIV(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = errorMessageByCode(errCode);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_FormalInput_getErrCode); /* prototype to pass -Wmissing-prototypes */
XS(XS_FormalInput_getErrCode)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "a");
    {
	ParseError*	a;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "ParseErrorPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    a = INT2PTR(ParseError *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"FormalInput::getErrCode",
			"a", "ParseErrorPtr");

	RETVAL = getErrCode(a);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_FormalInput_getErrLine); /* prototype to pass -Wmissing-prototypes */
XS(XS_FormalInput_getErrLine)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "a");
    {
	ParseError*	a;
	size_t	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "ParseErrorPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    a = INT2PTR(ParseError *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"FormalInput::getErrLine",
			"a", "ParseErrorPtr");

	RETVAL = getErrLine(a);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_FormalInput_getErrPos); /* prototype to pass -Wmissing-prototypes */
XS(XS_FormalInput_getErrPos)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "a");
    {
	ParseError*	a;
	size_t	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "ParseErrorPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    a = INT2PTR(ParseError *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"FormalInput::getErrPos",
			"a", "ParseErrorPtr");

	RETVAL = getErrPos(a);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_FormalInput); /* prototype to pass -Wmissing-prototypes */
XS(boot_FormalInput)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("FormalInput::constant", XS_FormalInput_constant, file);
        newXS("FormalInput::parserValidate", XS_FormalInput_parserValidate, file);
        newXS("FormalInput::errorMessageByCode", XS_FormalInput_errorMessageByCode, file);
        newXS("FormalInput::getErrCode", XS_FormalInput_getErrCode, file);
        newXS("FormalInput::getErrLine", XS_FormalInput_getErrLine, file);
        newXS("FormalInput::getErrPos", XS_FormalInput_getErrPos, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

