SET TEMP=c:\ask\CATS\tmp\
SET TMP=c:\ask\CATS\tmp\
SET PATH=%PATH%;C:\Program Files\Microsoft VS2003\Common7\IDE\
SET PATH=%PATH%;%CD%/spawner;%CD%/check
:SET SP_USER=cats
:SET SP_PASSWORD=cats20
:SET SP_RUNAS=0
SET SP_WRITE_LIMIT=30
SET SP_MEMORY_LIMIT=64
SET SP_DEADLINE=30
SET SP_REPORT_FILE=report.txt
SET SP_OUTPUT_FILE=stdout.txt
SET SP_HIDE_REPORT=1
SET SP_HIDE_OUTPUT=0
SET SP_SECURITY_LEVEL=1

:1
perl judge.pl
GOTO 1